summary: "Fetch an account based on the Account ID."

parameters:
  - name: accountId
    in: query
    required: true
    description: Field for Account ID.
    type: string

responses:
  200:
    description: Object containing the newly added account.
    schema:
      $ref: "#/definitions/components/Account"
  400:
    description: Bad request. Inputted information invalid. Ensure that the ID is a valid string.
  404:
    description: Cannot find object with inputted ID.
  500:
    description: Unexpected error.

definitions:
  import: "./definitions.yaml"
